name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RESOURCE_GROUP: cartoon-annotation-rg
  ACR_NAME: cartoonannotationacr
  APP_SERVICE_NAME: cartoon-annotation-app
  IMAGE_NAME: cartoon-annotation
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Build and Push to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_SERVICE_NAME }}
          images: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      
      - name: Configure App Settings
        run: |
          az webapp config appsettings set --resource-group $RESOURCE_GROUP --name $APP_SERVICE_NAME --settings \
            NODE_ENV=production \
            PORT=3000 \
            WEBSITES_PORT=3000 \
            COSMOS_ENDPOINT=${{ secrets.COSMOS_ENDPOINT }} \
            COSMOS_KEY=${{ secrets.COSMOS_KEY }} \
            COSMOS_DATABASE_ID=${{ secrets.COSMOS_DATABASE_ID }} \
            COSMOS_CONTAINER_ID=${{ secrets.COSMOS_CONTAINER_ID }} \
            AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }} \
            AZURE_STORAGE_CONTAINER_NAME=${{ secrets.AZURE_STORAGE_CONTAINER_NAME }} \
            NEXTAUTH_URL=https://${{ env.APP_SERVICE_NAME }}.azurewebsites.net \
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}